version: '3.3'
services:
  api:
    image: miniprojet-docker:v1
    container_name: api
    volumes:
      - $PWD/simple_api/student_age.json:/data/student_age.json
    networks:
      - mininet
  ihm:
    depends_on:
      - api
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    volumes:
      - $PWD/website:/var/www/html
    ports:
      - "8000:80"
    networks:
      - mininet
  registry:
      container_name: registry
      networks:
        - registry-network
      image: 'registry:2'
      ports:
        - "5000:5000"

  registry-ui:
      container_name: registry-ui
      networks:
        - registry-network
      image: 'joxit/docker-registry-ui:static'
      environment:
          - REGISTRY_URL="http://registry:5000"
          - REGISTRY_TITLE="AMIRA"
      ports:
          - "8080:80"

networks:
    mininet:
    registry-network:
